#!/usr/bin/env bash
#4badluck8isyourchance
for i in {1..10}
do
	    if [ $i -eq 4 ]
		        then
				        echo "bad luck"
					    elif [ $i -eq 8 ]
						        then
								        echo "good luck"
									    else
										            echo "Best School"
											        fi
											done
