#!/usr/bin/env bash
#this week is crazy never give up
FILE="school"

if [ -e "$FILE" ]; then
echo "school file exists"
if [ -s "$FILE" ]; then
echo "school file is empty"
else
echo "school file is empty"
fi
if [ -f "$FILE" ]; then
echo "school is a regular file"
fi
wlse
echo "school file does not exist"
fi
