#!/usr/bin/env bash
#first one

ANYTHING=/var/run/my_process.pid

case "$1" in
	start)
		./mange_my_process &
		echo $! > $ANYTHING
		echo "mange_my_process started"
		;;
	stop)
		kill "$(cat $ANYTHING)"
		rm $ANYTHING
		echo "mange_my_process stopped"
		;;
	restart)
		kill "$(cat $ANYTHING)"
		rm $ANYTHING
		./mange_my_process &
		echo $! > $ANYTHING
		echo "mange_my_process restarted"
		;;
	*)
		echo "Usage: mange_my_process {start|stop|restart}"
esac
